# Generated by Django 2.1.7 on 2019-05-15 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrow_Time', models.DateTimeField(auto_now_add=True)),
                ('Borrow_Duration', models.IntegerField()),
                ('Return_Time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '借阅信息',
                'verbose_name_plural': '借阅信息',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Auther', models.CharField(max_length=20)),
                ('KeyWords', models.CharField(max_length=20)),
                ('Pages_Start', models.IntegerField()),
                ('Pages_End', models.IntegerField()),
                ('Abstract', models.TextField()),
            ],
            options={
                'verbose_name': '论文信息',
                'verbose_name_plural': '论文信息',
            },
        ),
        migrations.CreateModel(
            name='Periodical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Phase', models.IntegerField()),
                ('Cycle', models.IntegerField()),
                ('Postal', models.CharField(max_length=20)),
                ('CN', models.CharField(max_length=20)),
                ('ISSN', models.CharField(max_length=20)),
                ('Locus', models.CharField(max_length=20)),
                ('Reserve', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Status', models.BooleanField()),
                ('Order_Time', models.DateTimeField(auto_now_add=True)),
                ('Responsibler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '期刊信息',
                'verbose_name_plural': '期刊信息',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='Belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='periodical.Periodical'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='Period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='periodical.Periodical'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
